apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-platform-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-platform-backend
  template:
    metadata:
      labels:
        app: streaming-platform-backend
    spec:
      containers:
        - name: backend-golang-container
          image: ajj132/streaming-platform-backend:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "128m"
            limits:
              memory: "128Mi"
              cpu: "256m"
          ports:
            - containerPort: 8082
