apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-platform-user-info-read-controller-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-platform-user-info-read-controller
  template:
    metadata:
      labels:
        app: streaming-platform-user-info-read-controller
    spec:
      containers:
        - name: user-info-read-controller-golang-container
          image: ajj132/streaming-platform-user-info-read-controller:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 8088
