apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-info-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-info-database
  template:
    metadata:
      labels:
        app: user-info-database
    spec:
      containers:
        - name: user-info-postgres-container
          image: ajj132/streaming-platform-user-info-database:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: login_db
          ports:
            - containerPort: 5432
