apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-storage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: ajj132/streaming-platform-video-storage-raw:latest
          args:
            - server
            - /data
          ports:
            - containerPort: 9000
          env:
            - name: MINIO_ACCESS_KEY
              value: "user"
            - name: MINIO_SECRET_KEY
              value: "password"
      volumes:
        - name: data
          emptyDir: {}
